---
# tasks file for mypostgres

- name: Install Postgres Repo
  ansible.builtin.yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    update_cache: yes
    state: present

- name: Install Postgres 13
  ansible.builtin.yum:
    name: postgresql13-server
    state: present
    update_cache: yes

  # check if database was initialized
- name: Check if config exists
  ansible.builtin.stat:
    path: "/var/lib/pgsql/13/data/postgresql.conf"
  register: postgresql_conf

- name: Init DB if config file not exists
  ansible.builtin.command: "/usr/pgsql-13/bin/postgresql-13-setup initdb"
  when: not postgresql_conf.stat.exists

- name: Enable and Start Postgresql
  ansible.builtin.service:
    name: postgresql-13
    state: started
    enabled: yes
    
- block:
  - name: Add database Slurm
    community.postgresql.postgresql_db:
      name: slurm
  
  - name: Create user for manage db Slurm
    community.postgresql.postgresql_user:
      name: slurm_db_user
      password: "slurm"
      role_attr_flags: "LOGIN"

  - name: Grant privileges to slurm_db_user on DB slurm
    community.postgresql.postgresql_privs:
      type: database
      db: slurm
      grant_option: yes
      privs: ALL
      roles: slurm_db_user

  become: yes
  become_user: postgres
